export const SET_SELECT_FILTER = "SET_SELECT_FILTER";
export const RESET_SELECT_FILTER = "RESET_SELECT_FILTER";
export const SET_RANGE_VALUE = "SET_RANGE_VALUE";
export const RESET_COUNT_ROWS = "RESET_COUNT_ROWS";
export const SET_COUNT_ROWS = "SET_COUNT_ROWS";
export const SET_NOT_FILTER_SELECT = "SET_NOT_FILTER_SELECT";
