export const LOAD_TOWERS_REQUEST = "LOAD_TOWERS_REQUEST";
export const LOAD_TOWERS_SUCCESS = "LOAD_TOWERS_SUCCESS";
export const LOAD_TOWERS_FAILURE = "LOAD_TOWERS_FAILURE";
export const CLEAR_TOWERS_LIST = "CLEAR_TOWERS_LIST";
