export const LOAD_ITEMS_REQUEST = "LOAD_ITEMS_REQUEST";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_FAILURE = "LOAD_ITEMS_FAILURE";
export const CLEAR_ITEMS_LIST = "CLEAR_ITEMS_LIST";
