/** Declaration file generated by dts-gen */

export function createConnection(opts: any): any;

export function createPool(opts: any): any;

export function createPoolCluster(opts: any): any;

export function geojeson(opts: any): any;